version: "3.8"
services:

  cheerlights_discordbot:
    build: .
    container_name: cheerlights_discordbot
    volumes:
      - /PATH/TO/cheerlights-discord-bot/data/config.json:/app/config.json
      - /PATH/TO/cheerlights-discord-bot/data/block_list.json:/app/block_list.json
    restart: unless-stopped