version: "3.8"
services:

  cheerlights_discordbot:
    build: .
    container_name: cheerlights_discordbot
    volumes:
      - <full path to bot folder>/log/:/app/log/
      - <full path to bot folder>/data/config.json:/app/config.json
      - <full path to bot folder>/data/block_list.json:/app/block_list.json
    restart: unless-stopped